version: '3.4'

services:
  web:
    build:
      dockerfile: ./docker/dev/php/Dockerfile
    depends_on:
      - database
      - redis
    volumes:
      - ".composer:/tmp/.composer"
      - "./symfony:/var/www/html"
    environment:
      - APACHE_SERVER_NAME=localhost
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "80:80"

  database:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  node:
    build:
      context: docker/dev/node
    volumes:
      - './angular:/usr/app'
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "4200:4200"

  mail:
    image: dockage/mailcatcher
    ports:
      - "1081:1080"

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  db_data:
