<?php

namespace App\Enum;

enum ApiErrorCode: string
{
    case GENERIC_UNAUTHORIZED = 'GENERIC_UNAUTHORIZED';
    case GENERIC_NOT_FOUND = 'GENERIC_NOT_FOUND';
    case GENERIC_SERVER_ERROR = 'GENERIC_SERVER_ERROR';
    case GENERIC_BAD_REQUEST = 'GENERIC_BAD_REQUEST';
    case GENERIC_MISSING_PAYLOAD = 'GENERIC_MISSING_PAYLOAD';

    case LOGIN_USERNAME_INVALID = 'LOGIN_USERNAME_INVALID';
    case LOGIN_PASSWORD_INVALID = 'LOGIN_PASSWORD_INVALID';
    case LOGIN_USER_NOT_FOUND = 'LOGIN_USER_NOT_FOUND';

    case DATE_INVALID = 'DATE_INVALID';
    case PRICE_POSITIVE = 'PRICE_POSITIVE';
    case COST_POSITIVE_OR_ZERO = 'COST_POSITIVE_OR_ZERO';
    case SHOE_SIZE_INVALID = 'SHOE_SIZE_INVALID';
    case SELLING_PRICE_INVALID = 'SELLING_PRICE_INVALID';
}
