export enum ErrorCode {
  GENERIC_OK = 'GENERIC_OK',
  GENERIC_UNAUTHORIZED = 'GENERIC_UNAUTHORIZED',
  LOGIN_USERNAME_INVALID = 'LOGIN_USERNAME_INVALID',
  LOGIN_PASSWORD_INVALID = 'LOGIN_PASSWORD_INVALID',
  GENERIC_NOT_FOUND = 'GENERIC_NOT_FOUND',
  LOGIN_USER_NOT_FOUND = 'LOGIN_USER_NOT_FOUND',
  GENERIC_BAD_REQUEST = 'GENERIC_BAD_REQUEST'
}
